"""Codex reverse-proxy image transformers.

Codex OAuth (chatgpt.com/backend-api/codex) does not expose
`/v1/images/generations`. Instead, images are generated by calling the
Responses API (`/responses`) with an `image_generation` tool attached. The
upstream streams SSE `response.output_item.done` events where the generated
image comes back as base64 inside `item.result`.

This module wraps that套壳:

1. request transformer:  OpenAI images payload  →  Responses+tool payload
2. SSE aggregator:       Responses SSE stream   →  standard images JSON
3. multipart parser:     /v1/images/edits body  →  normalized request dict
4. SSE frame synth:      for client stream=true, emit one fake
                         `image_generation.completed` frame with the final
                         base64 image.
"""

from __future__ import annotations

import base64
import json
import re
from collections.abc import AsyncIterator
from typing import Any

from src.core.logger import logger

# Tool options that map directly from OpenAI images request to the
# image_generation tool config.
_TOOL_PASSTHROUGH_KEYS: tuple[str, ...] = (
    "size",
    "quality",
    "background",
    "output_format",
    "output_compression",
    "moderation",
)


# --------------------------------------------------------------------------- #
# Request body transformation
# --------------------------------------------------------------------------- #


def transform_image_request_to_responses(
    body: dict[str, Any],
    context: dict[str, Any],
) -> dict[str, Any]:
    """Convert an OpenAI images payload into a Codex Responses payload.

    context keys:
        - mapped_model: str — model name resolved via provider_model_mappings
        - operation: "generate" | "edit" — derived by caller
        - multipart: dict | None — parsed multipart fields (for /images/edits)

    Returns a new dict; does not mutate input.
    """
    mapped_model = str(context.get("mapped_model") or body.get("model") or "").strip()
    if not mapped_model:
        raise ValueError("Codex image transform requires a mapped model")

    operation = str(context.get("operation") or "").strip().lower()
    if operation not in {"generate", "edit"}:
        operation = "edit" if context.get("multipart") else "generate"

    source = context.get("multipart") if operation == "edit" else body
    if not isinstance(source, dict):
        source = {}

    prompt = _coerce_str(source.get("prompt")) or "Generate an image."

    images = _collect_input_images(source)
    mask = _collect_mask_image(source)

    # Build the image_generation tool options
    tool: dict[str, Any] = {"type": "image_generation"}
    for key in _TOOL_PASSTHROUGH_KEYS:
        value = source.get(key) if source else body.get(key)
        if value is None:
            continue
        tool[key] = value
    if operation == "edit" or images or mask is not None:
        tool["action"] = "edit"
    if mask is not None:
        tool["mask"] = _build_mask_payload(mask)

    # Build the Responses `input` array
    if not images and mask is None:
        input_blocks: list[dict[str, Any]] = [
            {
                "role": "user",
                "content": prompt,
            }
        ]
    else:
        content: list[dict[str, Any]] = [{"type": "input_text", "text": prompt}]
        content.extend(images)
        if mask is not None:
            content.append(mask)
        input_blocks = [{"role": "user", "content": content}]

    payload: dict[str, Any] = {
        "model": mapped_model,
        "input": input_blocks,
        "tools": [tool],
        "tool_choice": "auto",
        "instructions": "you are a helpful assistant",
        "stream": True,  # Codex requires stream
        "store": False,
    }

    user = _coerce_str(body.get("user"))
    if user:
        payload["user"] = user

    return payload


# --------------------------------------------------------------------------- #
# SSE aggregation (reading Codex Responses stream)
# --------------------------------------------------------------------------- #


async def aggregate_codex_image_sse(
    byte_iter: AsyncIterator[bytes],
) -> dict[str, Any]:
    """Consume a Codex Responses SSE byte stream and produce a standard
    OpenAI images JSON response body.

    Returns a dict shaped like:
        {
            "created": 1234,
            "data": [{"b64_json": "...", "revised_prompt": "..."}],
            "usage": {"input_tokens": ..., "output_tokens": ..., ...}
        }
    """
    created: int | None = None
    completed_response: dict[str, Any] = {}
    images: list[dict[str, Any]] = []

    buffer = b""
    async for chunk in byte_iter:
        if not chunk:
            continue
        buffer += chunk
        while b"\n\n" in buffer:
            event_bytes, buffer = buffer.split(b"\n\n", 1)
            _consume_event(event_bytes, images, mutable_created := {"v": created},
                           mutable_completed := {"v": completed_response})
            created = mutable_created["v"]
            if mutable_completed["v"]:
                completed_response = mutable_completed["v"]

    # Handle trailing buffer (some servers don't emit terminating \n\n)
    if buffer.strip():
        _consume_event(
            buffer,
            images,
            mutable_created := {"v": created},
            mutable_completed := {"v": completed_response},
        )
        created = mutable_created["v"]
        if mutable_completed["v"]:
            completed_response = mutable_completed["v"]

    usage = _extract_usage(completed_response)
    return {
        "created": int(created or 0),
        "data": images,
        "usage": usage,
    }


def _consume_event(
    event_bytes: bytes,
    images: list[dict[str, Any]],
    created_ref: dict[str, Any],
    completed_ref: dict[str, Any],
) -> None:
    try:
        text = event_bytes.decode("utf-8", errors="ignore")
    except Exception:
        return

    data_lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("data:"):
            data_lines.append(stripped[5:].strip())
    for raw in data_lines:
        if not raw or raw == "[DONE]":
            continue
        try:
            obj = json.loads(raw)
        except Exception:
            continue
        if not isinstance(obj, dict):
            continue
        evt_type = str(obj.get("type") or "")
        if evt_type == "response.created":
            response = obj.get("response")
            if isinstance(response, dict):
                value = response.get("created_at")
                if isinstance(value, int):
                    created_ref["v"] = value
        elif evt_type == "response.output_item.done":
            item = obj.get("item")
            if not isinstance(item, dict):
                continue
            if item.get("type") != "image_generation_call":
                continue
            result = item.get("result")
            if not isinstance(result, str) or not result:
                continue
            images.append(
                {
                    "b64_json": result,
                    "revised_prompt": item.get("revised_prompt"),
                }
            )
        elif evt_type == "response.completed":
            response = obj.get("response")
            if isinstance(response, dict):
                completed_ref["v"] = response


def _extract_usage(completed_response: dict[str, Any]) -> dict[str, Any] | None:
    if not completed_response:
        return None
    tool_usage = completed_response.get("tool_usage")
    if isinstance(tool_usage, dict):
        image_gen = tool_usage.get("image_gen")
        if isinstance(image_gen, dict) and image_gen:
            return image_gen
    usage = completed_response.get("usage")
    if isinstance(usage, dict):
        return usage
    return None


# --------------------------------------------------------------------------- #
# Fake single-frame SSE for client stream=true compatibility
# --------------------------------------------------------------------------- #


def synthesize_stream_completed_frames(
    aggregated: dict[str, Any],
) -> bytes:
    """Given an aggregated images JSON, emit a single-frame SSE payload that
    mimics OpenAI's native `image_generation.completed` event plus `[DONE]`.

    This is used when the client sent `stream=true` but the candidate is
    Codex (which cannot deliver progressive partial_image frames). Many
    OpenAI-compatible clients only inspect the final completed event; this
    keeps them working.
    """
    data = aggregated.get("data") or []
    first = data[0] if data else {}
    if not isinstance(first, dict):
        first = {}
    completed = {
        "type": "image_generation.completed",
        "b64_json": first.get("b64_json"),
        "revised_prompt": first.get("revised_prompt"),
        "usage": aggregated.get("usage"),
        "created_at": aggregated.get("created"),
    }
    lines = [
        f"event: image_generation.completed\ndata: {json.dumps(completed, ensure_ascii=False)}\n\n",
        "data: [DONE]\n\n",
    ]
    return "".join(lines).encode("utf-8")


# --------------------------------------------------------------------------- #
# Multipart parsing for /v1/images/edits
# --------------------------------------------------------------------------- #


_MULTIPART_BOUNDARY_RE = re.compile(
    r'boundary\s*=\s*"?([^";]+)"?', re.IGNORECASE
)


def parse_multipart_image_edit(
    raw_body: bytes,
    content_type: str,
) -> dict[str, Any] | None:
    """Parse a multipart/form-data body from /v1/images/edits.

    Returns a dict of normalized fields compatible with
    transform_image_request_to_responses (operation="edit"):

        {
            "model": str,
            "prompt": str,
            "n": int | None,
            "size": str | None,
            "response_format": "b64_json",
            "user": str | None,
            "images": [{"type": "input_image", "image_url": "data:..;base64,.."}, ...],
            "mask": {"type": "input_image", ...} | None,
        }

    Returns None if the body cannot be parsed (missing boundary, malformed
    data, etc.).
    """
    if not raw_body or not content_type:
        return None
    match = _MULTIPART_BOUNDARY_RE.search(content_type)
    if not match:
        return None
    boundary = match.group(1).encode("ascii", errors="ignore")
    if not boundary:
        return None

    fields = list(_iter_multipart_fields(raw_body, boundary))
    if not fields:
        return None

    out: dict[str, Any] = {
        "images": [],
        "mask": None,
    }

    for field in fields:
        name = field["name"].strip()
        if not name:
            continue
        if name in ("image", "image[]", "images[]"):
            entry = _bytes_to_input_image(field["data"], field.get("content_type"))
            if entry is not None:
                out["images"].append(entry)
            continue
        if name == "mask":
            out["mask"] = _bytes_to_input_image(field["data"], field.get("content_type"))
            continue
        # Text fields
        try:
            text_value = field["data"].decode("utf-8", errors="replace").strip()
        except Exception:
            continue
        if name in ("n",):
            try:
                out[name] = int(text_value)
            except Exception:
                pass
        else:
            out[name] = text_value

    return out


def _iter_multipart_fields(body: bytes, boundary: bytes):
    """Minimal multipart/form-data parser — assumes CRLF line endings.

    Does NOT support chunked bodies or pathological malformed input; callers
    should wrap exceptions. Good enough for well-formed OpenAI SDK clients.
    """
    delim = b"--" + boundary
    end_delim = delim + b"--"

    # Split into parts
    chunks = body.split(delim)
    for raw in chunks:
        raw = raw.strip(b"\r\n")
        if not raw or raw == b"--":
            continue
        if raw.startswith(b"--"):
            continue
        # Each chunk = headers \r\n\r\n body
        sep = raw.find(b"\r\n\r\n")
        if sep < 0:
            continue
        header_block = raw[:sep].decode("latin-1", errors="ignore")
        data = raw[sep + 4 :]
        # Strip trailing CRLF that precedes next boundary
        if data.endswith(b"\r\n"):
            data = data[:-2]

        field: dict[str, Any] = {
            "name": "",
            "filename": None,
            "content_type": None,
            "data": data,
        }
        for line in header_block.split("\r\n"):
            if not line:
                continue
            lower = line.lower()
            if lower.startswith("content-disposition:"):
                name_match = re.search(r'name="([^"]+)"', line)
                if name_match:
                    field["name"] = name_match.group(1)
                filename_match = re.search(r'filename="([^"]*)"', line)
                if filename_match:
                    field["filename"] = filename_match.group(1)
            elif lower.startswith("content-type:"):
                field["content_type"] = line.split(":", 1)[1].strip()
        if field["name"]:
            yield field

    # Consume end_delim just to satisfy linter — actual split already handled it
    _ = end_delim


def _bytes_to_input_image(
    data: bytes,
    content_type: str | None,
) -> dict[str, Any] | None:
    if not data:
        return None
    mime = (content_type or "").strip() or "application/octet-stream"
    b64 = base64.standard_b64encode(data).decode("ascii")
    return {
        "type": "input_image",
        "image_url": f"data:{mime};base64,{b64}",
    }


# --------------------------------------------------------------------------- #
# Internal helpers
# --------------------------------------------------------------------------- #


def _coerce_str(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    trimmed = value.strip()
    return trimmed or None


def _collect_input_images(source: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    # Pre-normalized from multipart path
    raw = source.get("images")
    if isinstance(raw, list):
        for entry in raw:
            if isinstance(entry, dict) and entry.get("type") == "input_image":
                out.append(entry)
            else:
                normalized = _normalize_loose_image_value(entry)
                out.extend(normalized)
    # Loose JSON fields (e.g. body has {"image": "https://..."})
    for key in ("image",):
        value = source.get(key)
        if value is None:
            continue
        out.extend(_normalize_loose_image_value(value))
    return out


def _collect_mask_image(source: dict[str, Any]) -> dict[str, Any] | None:
    raw = source.get("mask")
    if raw is None:
        return None
    if isinstance(raw, dict) and raw.get("type") == "input_image":
        return raw
    normalized = _normalize_loose_image_value(raw)
    return normalized[0] if normalized else None


def _normalize_loose_image_value(value: Any) -> list[dict[str, Any]]:
    if isinstance(value, list):
        out: list[dict[str, Any]] = []
        for item in value:
            out.extend(_normalize_loose_image_value(item))
        return out
    if isinstance(value, str):
        url = value.strip()
        if not url:
            return []
        return [{"type": "input_image", "image_url": url}]
    if isinstance(value, dict):
        if "file_id" in value and value["file_id"]:
            return [{"type": "input_image", "file_id": value["file_id"]}]
        url = value.get("image_url") or value.get("url")
        if isinstance(url, str) and url.strip():
            return [{"type": "input_image", "image_url": url.strip()}]
        b64 = value.get("b64_json")
        if isinstance(b64, str) and b64:
            mime = value.get("mime_type") or "image/png"
            return [
                {
                    "type": "input_image",
                    "image_url": f"data:{mime};base64,{b64}",
                }
            ]
    return []


def _build_mask_payload(mask: dict[str, Any]) -> dict[str, Any]:
    if "file_id" in mask and mask["file_id"]:
        return {"file_id": mask["file_id"]}
    if "image_url" in mask and mask["image_url"]:
        return {"image_url": mask["image_url"]}
    return dict(mask)


__all__ = [
    "transform_image_request_to_responses",
    "aggregate_codex_image_sse",
    "synthesize_stream_completed_frames",
    "parse_multipart_image_edit",
]


# Logging the module load only in debug context
logger.debug("[CodexImage] image_transform module loaded")
